### ISSUE TITLE
interface:209

### ISSUE THREAD

**Issue by liulee** [hwhw/zigbee-lua#3]
## traceback:
 ./interfaces/zigbee.lua:209: attempt to call method 'set' (a nil value), stack traceback:
        ./interfaces/zigbee.lua: in function <./interfaces/zigbee.lua:206>
./luajit: ./lib/srv-epoll.lua:132: ./lib/ctx.lua:212: ./interfaces/zigbee.lua:209: attempt to call method 'set' (a nil value)
stack traceback:
        [C]: in function 'char_reader'
        ./lib/srv-epoll.lua:132: in function 'on_readable'
        ./lib/srv-epoll.lua:82: in function 'run'
        m.lua:6: in main chunk
        [C]: at 0x0000c370
## code & loc
``` 
      if d then
        self.devices:set(ieeeaddr, d) -- line 209
        self.devices:save()
      end
```
## maybe

 "self.device:set(...)", 
self or devices is null, or devices is not an valid object.
or the device has some error.

## env
arch:  arm71 on i.MX6UL
luajit: 2.05
mqtt: 1.6.2

btw. thanks for good work.

**Comment by liulee** [comment]
maybe:   self.device:set => self.device:insert

**Comment by hwhw** [comment]
Oh, dang, I overlooked this when redesigning the device database interface (my goal is to make the provisioning optional - as it does not really work that reliable for some Zigbee devices). Yes, insert() does this now. It will take me 3-4 days until I get to work on the code base again, unfortunately. I will update this issue than. Thanks for the report!

**Comment by hwhw** [comment]
I did not get around to test it, but it should work now. I'm leaving this open until you or me can confirm this.

Note that there's been changes in how the application framework and the stuff I've named "environment" do interact. It also makes it more flexible when it comes to managing different configurations. See the environment example files for, well, examples :-)

**Comment by hwhw** [comment]
Considering this fixed now.
