### ISSUE TITLE
Please unbundle dependencies

### ISSUE THREAD

**Issue by Perlovka** [hwhw/zigbee-lua#4]
Hi, It is possible to unbundle all dependencies from this repo?

I mean all external libraries, including those ffi_* than have separate repos. All libraries should go into their place in system. This will ease package maintenance.

Also, json-lua could be replaced with cjson, which is available almost in every distro, even in RHEL ;).

I've added some of them in my gentoo overlay (https://github.com/Perlovka/portage-overlay/tree/master/dev-lua), but still using a "hack" to unbundle them from code (https://github.com/Perlovka/portage-overlay/blob/30641bcd9310ec0134f3a16f1d268ef99b29ca15/dev-lua/zigbee-lua/zigbee-lua-0.1_pre20190529.ebuild#L47)

Thanks.

**Comment by Perlovka** [comment]
Also, please consider to release ffi_* libraries, at least as 0.1 version, this will ease packaging too )

**Comment by hwhw** [comment]
Hm, I can certainly release them, but I do not really see how this improves matters much - it's all just a submodules init / submodules update away? What exactly do you mean by "unbundle"?

json-lua is a pure Lua thingy, so why have another external dependency with cjson?

A bit more explanation: without using MQTT and/or HTTP (server), there's no external non-Lua dependencies aside from Lua(JIT) itself and a Linux kernel. I consider this a plus, actually.

**Comment by Perlovka** [comment]
By "unbundle" I mean that package should not provide external code as git submodule or just copy a piece of it. If dependency has its own repo, package manager should install it as a dependency, not bundle all deps in one package. This is how package management works. 

Let's say you wrote one more app using libmosquitto. In your way, you will end with two packages containing same piece of code twice. And when you change libmosquitto itself, you should repackage both applications, instead of just update libmosquitto.

cjson - just because almost all distros already have it in their repos. So this is more easy just to install it and not find someone who will package it for you. Also it's usually faster than pure lua implementations (https://github.com/efelix/lua-cjson/blob/master/performance.txt)

**Comment by hwhw** [comment]
I would not consider all the submodules being separate entity like packages on a linux distro. They are certainly separate entities, though - even if just for the organization of software I write. No, I'll leave it like this. *If* someone were to package zigbee-lua for some distribution, I leave it to that person to un-vendor the dependencies if that really was necessary, but I'm very much in doubt. If I were to package this, I would just package the code of this repo along with the submodules and not even try to make separate packages out of them. It's all just a bunch of Lua source code. E.g. the ffi_* submodules, they are not worth to be made packages. And why not make them submodules? I might be or already am using them in other software projects, so it's just a bit of deduplication to include them as submodules. Similar for the "external" chunks.

cjson: Here, too, I will stay with a pure Lua solution. As for the reasoning, it's the same: I'm fine with vendoring json-lua. This all boils down to chosing priorities - mine is to keep all the code tightly integrated.

**Comment by Perlovka** [comment]
> If someone were to package zigbee-lua for some distribution, I leave it to that person to un-vendor the dependencies if that really was necessary

The problem is that for unbundle it properly, that person should patch sources, to change all **require** paths.
Anyway, it's your code, and your desicion. Thanks for the answer )

**Comment by hwhw** [comment]
Yes, and in any case feel encouraged to ask and question the design decisions! I'm not that stubborn usually ;-)
